### ISSUE TITLE
Monstercat visualizer goes slow

### ISSUE THREAD

**Issue by redsregards** [MarcoPixel/Monstercat-Visualizer#76] opened 2017-08-12 17:49 UTC
After some time the visualizer will go slow. The bars act like they in slow mo or something. I tried lowering the sound resolution but that doesn't help.

**Comment by MarcoPixel** [comment] 2017-08-13 08:56
It seems that you have an memory leak, did you check in Task-Manager if Rainmeter is using a lot of memory when it happens? If yes, please make a screenshot and post it here.

Also you please send a screenshot from the debug log of Rainmeter (https://docs.rainmeter.net/manual/user-interface/about/) and  please write down your OS version, Rainmeter version, GPMDP plugin version and skin version so we can propertly go through all the possible issues you're facing.

**Comment by redsregards** [comment] 2017-08-14 21:21
![taskrain](https://user-images.githubusercontent.com/30959984/29291905-1c5caeec-8113-11e7-957c-ee97cbb0fa80.png)
OS: Windows 10 home version 1607
Rain meter: 4.0.0 r2756 64-bit
GPMDP: 4.4.0 
Skin version:  gpmdp-arc-theme i can't find the version of the skin but ik it's the newest version.

**Comment by MarcoPixel** [comment] 2017-08-14 21:39
@tjhrulz This seems like a memory leak on the GPMDP plugin, any idea what would cause it?

**Comment by tjhrulz** [comment] 2017-08-14 21:47
That is not a memory leak, that seems pretty normal RAM usage. However that CPU is out of control and it may have something to do with the song not being found in the queue. I do have some questions if you could answer/test them.
There is no version 4.4.0 for the plugin, it should be listed in your plugins tab.
What was the metadata for the song you were listening to?
If you skip to a different song does it go away? 
If you unload all the components to Monstercat Visualizer does it go away?
Is it always there the moment the refresh all the rainmeter or does it take several minutes?

**Comment by redsregards** [comment] 2017-08-15 05:21
[Rainmeter.txt](https://github.com/MarcoPixel/Monstercat-Visualizer/files/1224201/Rainmeter.txt)

GPMDP: 1.2.0.0
What was the metadata for the song you were listening to? idk how to find that.
If you skip to a different song does it go away? No
If you unload all the components to Monstercat Visualizer does it go away? No
Is it always there the moment the refresh all the rainmeter or does it take several minutes? It's always there

The only way I have been able to get rid of it is to close and re open rainmeter, then at times when I do that the visualizer will only stay stationary as a line.

**Comment by tjhrulz** [comment] 2017-08-17 22:30
Try downloading 1.4 and see if that helps. https://github.com/tjhrulz/GPMDP-Plugin/releases/download/1.4/GPMDP.Plugin_1.4.rmskin

However thinking about it now the only thing that can use that kind of CPU is the mouse plugin. Some local changes were made to take advantage of the newer update so maybe try doing a manual install and see if that does anything. https://github.com/MarcoPixel/Monstercat-Visualizer#manual-installation

**Comment by redsregards** [comment] 2017-08-20 20:49
The visualizer is still going slow after the manual install.

**Comment by tjhrulz** [comment] 2017-08-20 21:00
And doing the plugin update after? I noticed you had some other skins installed, I think it may be one of them causing it as I have tried to look for any issues and have found nothing.

**Comment by redsregards** [comment] 2017-08-21 13:37
I went and took out my others skins and it's still slow imma just try and do a full wipe of rain meter

**Comment by redsregards** [comment] 2017-08-21 16:12
Nope still going slow

**Comment by tjhrulz** [comment] 2017-08-22 21:39
🤷‍♂️ I got nothing. There is no indication that there should be anything going wrong like that. Maybe it is a sound issue but that would unload itself after a while.

**Comment by redsregards** [comment] 2017-08-24 04:01
[.settings.txt](https://github.com/MarcoPixel/Monstercat-Visualizer/files/1247679/default.settings.txt)

**Comment by tjhrulz** [comment] 2017-08-24 05:49
Yeah that is the only area I could think of that could cause that issue and it all looks fine. At this point it has gotta be a rainmeter or a computer issue. Everything we have tested seems to indicate it is not the monstercat visualizer.

Sorry we could not figure out the source of the issue though and have to leave you with that vague response.

**Comment by tjhrulz** [comment] 2017-08-29 00:27
@redsregards I have found the cause of the issue. It seems to have been caused by being on the beta branch of rainmeter. I will have a new build up of GPMDP plugin shortly and it will be included in the bug fix update we have planned for monstercat visualizer which should happen soon.

**Closed** 2017-08-29 00:48 UTC
Labels: bug

**Comment by tjhrulz** [comment] 2017-08-29 00:50
Feel free to either manually update or wait for the next release.

Really sorry that I did not catch and fix this issue sooner. You get 1 free priority bug fix in the future :P

**Comment by Cryo-Bytes** [comment] 2020-06-03 07:02
sorry i am having this problem currently, what should I do to fix it, I use monstercat visualizer
