### ISSUE TITLE
i fixed the song info thing for spotify

### ISSUE THREAD

**Issue by eerwwe** [marcopixel/Monstercat-Visualizer#226] opened 2018-10-08 17:09 UTC
![image](https://user-images.githubusercontent.com/28791625/46623108-3c750b00-caf2-11e8-9e4f-61ab82ea6849.png)
 go to chrome settings, go to the bottom, hit advanced, go down to the bottom again and hit "Continue running background apps when Google Chrome is closed". than go to monstercat setting, hit media player, than click webplayer, than click spotify. ez. took forever to find a fix.
i love monstercat 
edit: you dont have to keep chrome open for it to work and it wont use any extra ram, cpu or disk as long if u dont have a crypto currency or vpn switch chrome extensions active.

**Comment by eerwwe** [comment] 2018-10-08 17:15
im sorry for putting this in issues but i didn't know where else to put it

**Comment by McGuffery** [comment] 2018-10-13 03:40
It didn't work fro me, it just keeps flickering the song info over and over again. (thank you though)

**Comment by Royalgamer06** [comment] 2018-11-02 20:05
I don't have Web NowPlaying?

**Comment by LordAres24** [comment] 2018-11-19 16:19
It's not solving the issue for me  :'(

**Comment by eerwwe** [comment] 2018-11-20 19:17
a lil update about this. last week i did an update on spotify and now it dosent work. if i find a new way ill let u know

**Comment by tjhrulz** [comment] 2019-05-04 06:06
This makes no sense as that would not fix it, you either had spotify open in your browser as well or has khanas's WebNowPlaying Spotify injector added to the desktop app.

Regardless this is a duplicate of issue #191 and this will be closed

**Closed by tjhrulz** 2019-05-04 06:06 UTC
