### ISSUE TITLE
Song Information Not Show Name Song When Play Music

### ISSUE THREAD

**Issue by koonpeet9880** [MarcoPixel/Monstercat-Visualizer#199] opened 2018-07-25 11:32 UTC
[( [Song Information Not Show Name Song When Play Music] )]

### Description

[Song Information Not Show Name Song When Play Music | Found Issue By Windows Update]

### Versions

[IMPORTANT: Please fill out the version numbers so we can properly look for your issue.]

[You can remove this section when posting an feature request]

* Rainmeter Version: [4.2.0 r3111]
* OS Version: [Windows 10 Pro 1803 64-bit (build 17134) - Thai (1054)]
* Skin Version: [2.0.2]
* Spotify Version: [1.0.85.257.g0f8531bd (Windows Store version)]

### Additional notes/images
![image](https://user-images.githubusercontent.com/25414778/43198054-6f0d1378-9037-11e8-8713-bcfeeee13d0e.png)

![image](https://user-images.githubusercontent.com/25414778/43197756-558dd532-9036-11e8-91f5-2667dcde9afc.png)

[If you have any additional infos you can give us, please write them down]

**Comment by MarcoPixel** [comment] 2018-07-25 11:52
Duplicate of #191

**Closed by MarcoPixel** 2018-07-25 11:52 UTC

**Comment by koonpeet9880** [comment] 2018-07-25 11:56
![image](https://user-images.githubusercontent.com/25414778/43199528-7d30440c-903c-11e8-929b-27471be0e201.png)
