### ISSUE TITLE
Not showing song info in Spotify

### ISSUE THREAD

**Issue by MiPiNi** [MarcoPixel/Monstercat-Visualizer#205] opened 2018-07-30 12:53 UTC
### Description

[Visualizer is not showing song info for Spotify music, keeps viewing N/A. I tried to reinstall skin, reboot pc and reinstall spotify also I run Spotify as administrator but nothing changed.]
![image](https://user-images.githubusercontent.com/26858440/43398230-bfe82ca0-9407-11e8-815c-f115e2164143.png)

### Versions

* Rainmeter Version: [4.2.0 r3111 64-bit]
* OS Version: [Windows 10 Pro 1709 64-bit]
* Skin Version: [2.0.2]
* Spotify Version: [Plugin: 2.1.5 App: 1.0.86.337.ga8d5cef9]

### Additional notes/images

[Song info in webnowplaying works properly]
![image](https://user-images.githubusercontent.com/26858440/43398331-0c9a47fe-9408-11e8-9fc2-d80143764bf7.png)

**Comment by MarcoPixel** [comment] 2018-07-30 18:32
Duplicate of #191

**Closed by MarcoPixel** 2018-07-30 18:32 UTC
