### ISSUE TITLE
Extra addition to the progress bar

### ISSUE THREAD

**Issue by jcs021102** [marcopixel/Monstercat-Visualizer#252] opened 2019-06-13 16:05 UTC
### Description

It would be nice if the progress bar (which recently got patched) could b eset seperatly to the visualiser. This would lead to better customisation as well as the option to set the visualiser clickable through while still keeping the functionality from the progress bar.

**Comment by marcopixel** [comment] 2019-06-29 10:13
Duplicate of #251.

**Closed by marcopixel** 2019-06-29 10:13 UTC
