### ISSUE TITLE
Spotify update breaks Rainmeter playback controls

### ISSUE THREAD

**Issue by Tirith2708** [MarcoPixel/Monstercat-Visualizer#144] opened 2018-03-03 17:16 UTC
Title is pretty self explanatory. Pause/Next track/Last track on cover and progress bar are animated like they should but they don't do anything. It work's with AIMP but doesn't with Spotify (i run two separate instances of visualizer for those apps).

BR

**Comment by tjhrulz** [comment] 2018-03-03 17:26
Spotify desktop or browser?

**Comment by Tirith2708** [comment] 2018-03-03 17:26
Desktop

**Comment by tjhrulz** [comment] 2018-03-03 17:52
Progress bar does nothing on desktop and unless a Windows update/Spotify removed support for media playback buttons there is no way the others stopped working. I'll look into it when I get home.

**Comment by tjhrulz** [comment] 2018-03-04 04:42
It would seem that as of update 1.0.75.483.g7ff4a0dc Spotify changed its rendering system and when they did so they forgot to add a class to the main window, leaving it the default chrome rendering system name.

Likely this was a mistake and it will be changed in the next update, if not then I will work around this on the Rainmeter side of things.

**Comment by tjhrulz** [comment] 2018-03-14 17:37
Looks like it may be fixed in the next Spotify update, until then spotify premium users can just do a manual install.

**Comment by tjhrulz** [comment] 2018-03-23 23:11
Confirmed to still be an issue in version 1.0.77.338.g758ebd78

**Comment by jaspm2004** [comment] 2018-04-23 19:30
hey guys...i just found this visualizer, nice job! 

im having this problem too. still an issue?

**Comment by tjhrulz** [comment] 2018-04-24 03:37
It is, and Spotify has confirmed that they will not be reverting their change that caused the issue.

I am in the middle of another project I am working on for Rainmeter that should be wrapping up shortly, once that is done I will work on working around this in a future Rainmeter beta.

Until then just keep an eye on this issue/the Rainmeter 4.2 beta changelog and with any luck it will be resolved before to much longer.

**Comment by tjhrulz** [comment] 2018-06-16 06:37
Whoops forgot to close this issue when it was fixed in rainmeter.

As of the Rainmeter beta 4.2 build 3074 the issue has been fixed. 

Marco should we look at undoing then having the button commands being Spotify plugin based?

**Closed** 2018-06-16 06:37 UTC
Labels: bug, external-issue, spotify
