### ISSUE TITLE
Spotify not working/returning any data

### ISSUE THREAD

**Issue by AMountainGoat** [MarcoPixel/Monstercat-Visualizer#27] opened 2017-03-09 23:57 UTC
I've had this plugin for a while and it's been working fine for a week. However, yesterday, however, the title and artist got permanently stuck to N/A and the album art to the last song I had listened to.

Running Windows 10 with Spotify Premium. The plugin is running on my second monitor. The only other Rainmeter plugin I have is a Radial Clock widget, so there should be no incompatibility with other Rainmeter plugins. I've re-installed both Spotify and Monstercat Visualizer but no dice. Switching playlists or logging out and back in has not worked either. 

The program might have gotten confused due to me picking up from my playlist on my phone after starting it on my computer after the PC was shut off. So when I started up again, my PC Spotify was still set on the same playlist but a couple songs ahead. Note that Windows 10 still properly recognizes what I'm listening to (When you press play with Media Keys an annotation appears on the top left with album cover, title, artist. Similar to when you adjust your volume slider.)

I could post my .ini files but they should be untouched due to me doing a fresh re-install. 
Note: the visualizer still works, so the plugin is active.

Thanks for the help.

**Comment by tjhrulz** [comment] 2017-03-10 00:13
Marco is aware of the issue, from my debugging of the Spotify plugin it seems the plugin is getting an oauth code but Spotify is saying it is bad. I have a feeling that Spotify changed/deprecated the way the codes are given out.

**Comment by Ragod12** [comment] 2017-03-10 00:51
I'm having the same problem, It was playing fine until this morning, about 5 hours ago, I think spotify updated, but you'd have to look in on that.

The problems are the same N/A for the title and a stuck Logo for the last song I listened to, 
I tried reinstalling the visualiser to no avail. I think it's just a problem with the code recognizing the *maybe*  changed spotify codes for songs, like @tjhrulz stated, but again i'm not sure.

**Comment by HorusHeretic** [comment] 2017-03-10 11:35
Can confirm I've been having the same problem since last night.

**Comment by DAHAMMEROFGOD** [comment] 2017-03-11 03:05
Same here. Wednesday night it was fine but Thursday I was experiencing the same N/A & cover album issue as mentioned above. I'm still seeing the same issue today so I'm not sure if an uninstall/reinstall is in order. As an additional note, I was having issues moving the Song Name (Left) visualizer past a certain point on my screen. Even though there was more area on the screen to use it was blocking me from dragging it to that section. Just for reference, I have a 3 monitor setup and it was fine the night before (without having made any setting changes).

**Comment by Ragod12** [comment] 2017-03-11 05:35
Still looks like the bug's consisting, Still displays N/A and has a stuck logo.

**Comment by olufade** [comment] 2017-03-11 07:25
Still on N/A as well. Just redownloaded after a fresh install of windows.

**Comment by GMR516** [comment] 2017-03-11 21:39
Can confirm. Have this issue as well.

**Comment by imhobson** [comment] 2017-03-11 21:55
Same issue here, was working fine for months and then within the last 2 days it just stopped working, showing the most recent album art and N/A for the song.

**Comment by lurquhar1221** [comment] 2017-03-11 23:01
Can confirm.

**Comment by COLAMAroro** [comment] 2017-03-12 00:44
Confirming too.
A possible solution can be found in Windows 10 directly?
[http://i.imgur.com/z1M4jRz.png](url)
By using the "Volume Up" button, Windows recognize Spotify and, allow me to control music from Spotify, and give me song name, author and cover

**Comment by tjhrulz** [comment] 2017-03-12 02:15
Too everyone trying to find a solution unfortunately there is none, something happened server side so that the codes given for authentication are not accepted by spotify. The only thing that would maybe fix it is rolling back and as far as I know it won't fix it as spotify changed/disabled the authcodes that are given out.

Unfortunately this is just a sit tight until .raptor can provide an updated plugin that fixes these issues. You can watch for updated here: https://forum.rainmeter.net/viewtopic.php?f=18&t=17077

If I become aware of what is going wrong I do have in my possession the source code for the plugin and could build a hotfix but as of right now it just looks like spotify is giving bad authcodes.

**Comment by Matuir** [comment] 2017-03-13 04:38
CAN CONFIRM, IT SAYS N/A

**Comment by ASAPKush** [comment] 2017-03-15 11:47
updates?

**Comment by GMR516** [comment] 2017-03-15 16:02
None yet ASAPKush. The author has been quiet about what's going on. Sit tight.

**Comment by MarcoPixel** [comment] 2017-03-15 20:06
Just a quick update, the creator of the spotify plugin is currently looking into this issue and as soon as a update gets released i will inform you guys here on github. There is also currently no workaround as this is not only affecting SpotifyWebHelper.exe but the whole authentification process for Spotify on Desktop.

So the only thing you can do is wait for a new update.

**Comment by tjhrulz** [comment] 2017-03-16 20:17
Update: The root cause of the issue has been found, I am currently working on a hotfix for the plugin and will submit a pull request to .raptor with my fixes shortly.

**Comment by tjhrulz** [comment] 2017-03-16 22:09
So good new everyone, I have fixed the plugin with some caveats. 
1. The source code I have for the spotify plugin is based on version 1.2.4.1 so unfortunately whatever was added in 1.2.5 is not included in this hotfix.
2. Out of respect for .raptor I have made the version number 1.2.4.2 so you will have to click the checkbox to install the plugin. A warning will popup telling you not to do this ignore it. Since I need a skin in there I included the default skin included in his plugin, you do not need to install that.
3. I have submitted a pull request for my changes to be added to the original spotify plugin, thus out of respect to .raptor I will not be posting this anywhere else. If he does not get back to me in a few days I will assume he is no longer updating his plugin but until then please keep redistributing this to a minimum.

Aside for the change to fix spotify plugin functionality this also returns the log statement that spotify is not running back to being a debug statement and not a warning.

DL:https://mega.nz/#!jkhDUJhJ!VBatVBRCQwM-bsQG7sqeibZRe1liMwj4rwsvuQLxInE

**Comment by HorusHeretic** [comment] 2017-03-16 22:20
Thank you very much for the fix! Works fine now, you're fantastic.

**Comment by MarcoPixel** [comment] 2017-03-16 22:20
Working so far without issues, let's just hope that .raptor releases an update fast enough to bundle it with the visualizer.

Great work as always @tjhrulz! 👍

**Comment by GMR516** [comment] 2017-03-16 23:12
Awesome. Thanks for the fix. Good job.

**Comment by NighthawkSLO** [comment] 2017-03-17 11:23
raptor himself has now [updated the plugin](https://forum.rainmeter.net/viewtopic.php?f=18&t=17077)

**Comment by tjhrulz** [comment] 2017-03-17 14:08
Yup seems he merged my pull request, go get the official update here: https://forum.rainmeter.net/download/file.php?id=13902&sid=e1d22d7d2ebd3103e5fcaa64f8d2c4a4

**Comment by MarcoPixel** [comment] 2017-03-17 14:20
Yeah, already saw it. I will push out an update later today (about 5hrs from now) because i'm still at work. 

If you don't want to wait just download the .rmskin @tjhrulz posted in here.

**Closed** 2017-03-17 18:58 UTC
Labels: bug
