### ISSUE TITLE
Not supporting Chinese (Maybe all the CJK characters?)

### ISSUE THREAD

**Issue by NoobTW** [MarcoPixel/Monstercat-Visualizer#139] opened 2018-02-15 13:11 UTC
### Description

It doesn't support Chinese characters. Sometimes it shows N/A, and sometimes it shows garbled text.

### Versions

* Rainmeter Version: 4.2.0 Beta
* OS Version: Windows 10 17074
* Skin Version: 1.8.1
* Spotify Version: 1.0.73.345.g6c9971ef

### Additional notes/images

![image](https://user-images.githubusercontent.com/9292238/36258103-7194d0b6-1294-11e8-9077-230c809150f5.png)
![image](https://user-images.githubusercontent.com/9292238/36258134-80a6b2ea-1294-11e8-8104-4cf90b18bd81.png)

**Comment by MarcoPixel** [comment] 2018-02-15 14:28
Duplicate of #74, please follow the steps there to obtain a different font which supports the characters.

**Closed by MarcoPixel** 2018-02-15 14:28 UTC
