### ISSUE TITLE
Artist and song name not detected

### ISSUE THREAD

**Issue by FcoMGX** [MarcoPixel/Monstercat-Visualizer#196] opened 2018-07-23 09:09 UTC
### Description
The skin doesn't detect the artist and song name while spotify is launched

### Versions
* Rainmeter Version: 4.2  - r3111
* OS Version: Windows 10 Home - Version: 1607
* Skin Version: 2.02
* Spotify Version: 1.0.74.380

### Additional notes/images
![rainmeter_error](https://user-images.githubusercontent.com/41569987/43067799-be019902-8e68-11e8-9c4c-6767a4c8f180.jpg)

**Comment by hobhobuk** [comment] 2018-07-23 17:45
Same issue here.

**Comment by MarcoPixel** [comment] 2018-07-23 18:04
Duplicate of #191.

**Closed by MarcoPixel** 2018-07-23 18:04 UTC
