### ISSUE TITLE
VLC not showing song info or thumbnail

### ISSUE THREAD

**Issue by Dexy2811** [marcopixel/Monstercat-Visualizer#305] opened 2020-06-27 21:16 UTC
### Description

Doesnt display music info or thumbnail.
ive updated rainmeter, reinstalled/updated Monstercat-Visualizer.

### Versions

[IMPORTANT: Please fill out the version numbers so we can properly look for your issue.]

* Rainmeter Version: [ 4.4.0.3382 beta (64 bit) ]
* OS Version: [Windows 10 Pro version 2004]
* Skin Version: [2.1.0]
* VLC Version: [VLC Version: 3.0.11 Vetinari]

### Additional notes/images

![bilde](https://user-images.githubusercontent.com/38790678/85932396-18f88200-b8cc-11ea-8005-831750d6fa70.png)

**Comment by marcopixel** [comment] 2020-10-23 13:03
Duplicate of #108, please visit that issue for more information.

**Closed by marcopixel** 2020-10-23 13:03 UTC
