### ISSUE TITLE
Spotify: Metadata not getting fetched

### ISSUE THREAD

**Issue by Yoongin** [MarcoPixel/Monstercat-Visualizer#99] opened 2017-10-09 16:49 UTC
So, the song cover isn't changing, I only installed the this visualizer on the Friday after I was done with school. Everything was working just fine at home, but today at school, the cover art and song title isn't changing but the visualizer is still working fine.

**Comment by MarcoPixel** [comment] 2017-10-13 22:14
Might be a duplicate of #38, check out the solutions there and see if the are working.

**Comment by tjhrulz** [comment] 2017-11-02 02:36
Closing due to inactivity.

**Closed by tjhrulz** 2017-11-02 02:36 UTC
Labels: bug, Spotify
