### ISSUE TITLE
Cover art and song info doesnt show

### ISSUE THREAD

**Issue by oxplfusion** [MarcoPixel/Monstercat-Visualizer#203] opened 2018-07-28 03:21 UTC
* Rainmeter Version: 4.2 Final Release - r3111
* OS Version: 10.0.17134 Build 17134
* Skin Version: 2.0.2
* Spotify Version: 1.0.86.337.ga8d5cef9

ive tried reinstalling everything on rainmeter and restarting my pc but the cover art and song info doesnt show up and it randomly stopped working one day for no reason

**Comment by notNSANE** [comment] 2018-07-28 11:37
can confirm, stopped working about a week and half ago?

**Comment by MarcoPixel** [comment] 2018-07-28 12:29
Duplicate of #191.

**Closed** 2018-07-28 12:29 UTC
