### ISSUE TITLE
Visualizer not displaying artis, song or cover.

### ISSUE THREAD

**Issue by RedHawk13** [MarcoPixel/Monstercat-Visualizer#31] opened 2017-03-15 21:02 UTC
Using Spotify, used to work fine until a week ago where it seems to have gotten stuck on a song cover and the artist and song name is "N/A" and it doesn´t display the song length.

I have Spotify set as my media player and all the fixes from the settings don´t work.

**Comment by MarcoPixel** [comment] 2017-03-15 21:04
Duplicate of #27, closed.

**Closed by MarcoPixel** 2017-03-15 21:04 UTC
