### ISSUE TITLE
Duration and Position never uses dynamic color of text but uses static color of text

### ISSUE THREAD

**Issue by tjhrulz** [MarcoPixel/Monstercat-Visualizer#44] opened 2017-04-18 18:54 UTC
The Duration, Position, and divider strings in the cover use the text color to change their color. However if "Use dynamic color for song title and artist" is turned on they do not use but instead continue to use the static color. Since the media controls are always white this means that it is the only thing that is colored.

Should these be updated to just always be white like the media controls? Or should they be updated to use the text dynamic color (And maybe the media controls as well)?

**Comment by tjhrulz** [comment] 2017-04-18 18:59
Also if both "Enable dynamic cover art colors" and "Use dynamic color for song title and artist" are on the text color is set to default color between song instead of the text color.

**Comment by MarcoPixel** [comment] 2017-05-13 19:20
This is intended because it needs to be better visible and also consistent with the play/pause and rewind/forward buttons. I'm gonna close this issue because it is working as intended.

**Closed by MarcoPixel** 2017-05-13 19:20 UTC

**Comment by tjhrulz** [comment] 2017-05-13 19:22
Yeah I had noticed that during my performance test that it did not work well. But they will use the static text color if you set one and do not always stay white like the button do.

**Comment by MarcoPixel** [comment] 2017-05-13 19:25
Okay, thanks for the reply. Gonna change that the static color changes it tho, because i want it to be consistent.
