### ISSUE TITLE
The song information doesn't work!

### ISSUE THREAD

**Issue by LonelyFox48** [MarcoPixel/Monstercat-Visualizer#204] opened 2018-07-29 17:58 UTC
I don't know what happened, I tried to open the skin and the song information doesn't work.

* Rainmeter Version: 4.2.0 r3111
* OS Version: Windows 7 Ultimate 64-bit (build 7601)
* Skin Version: 2.0.2
* Spotify Version: 1.0.60.492.gbb40dab8 

![problema](https://user-images.githubusercontent.com/41872970/43368730-55ba9cca-9338-11e8-9b02-d296cabb5811.png)

**Comment by MarcoPixel** [comment] 2018-07-29 19:58
Duplicate of #191

**Closed by MarcoPixel** 2018-07-29 19:58 UTC
