### ISSUE TITLE
Auto media player recognition?

### ISSUE THREAD

**Issue by MythDanny** [marcopixel/Monstercat-Visualizer#302] opened 2020-06-10 09:29 UTC
I use spotify a lot, but I often use musicbee to play stuff I downloaded that's not available on spotify. It's not much of a problem, but it's a hassle to have to go to the settings of the visualizer and select the media source everytime I want to switch media players. I'd just like to suggest adding a feature that makes the visualizer auto recognize the media player. (And no I don't want to use the option that lets the visualizer pick up all system sounds)

**Comment by marcopixel** [comment] 2020-10-23 13:10
Duplicate of #280.

**Closed by marcopixel** 2020-10-23 13:10 UTC
