### ISSUE TITLE
Sptofiy Plugin wont work for visualizer 

### ISSUE THREAD

**Issue by burgeronsteam** [MarcoPixel/Monstercat-Visualizer#212] opened 2018-08-16 01:23 UTC
### Description

I keep trying to use Spotify for my visualizer, and it just doesn't work

### Versions

* Rainmeter Version: 4..0 r3111 64-bit
* OS Version: Windows 10 Home 64-bit
* Skin Version: 2.0.2 (Newest as of August 15 2018)
* Spotify Version: 2.1.5

### Additional notes/images

I've restarted Rain, Spotify, and PC. Nothing seems to work.

**Comment by MarcoPixel** [comment] 2018-08-17 16:32
Duplicate of #191.

**Closed by MarcoPixel** 2018-08-17 16:32 UTC
