### ISSUE TITLE
Google Play Desktop Player No Album Art

### ISSUE THREAD

**Issue by oddlock** [MarcoPixel/Monstercat-Visualizer#129] opened 2018-01-23 01:07 UTC
### Description

Have opened up firewall settings. I get the GPMDP popup saying the player is being controlled by the visualizer but still get no album art. 

No album art showing when I choose the webplayer and go to google play that way.
### Versions

* Rainmeter Version: 4.2r3018

* OS Version: Win 10
* Skin Version:1.4.1
![capture](https://user-images.githubusercontent.com/35711761/35252721-b7f9c040-ffaf-11e7-9d30-2eb8b50e6086.JPG)

**Comment by tjhrulz** [comment] 2018-01-23 01:25
The image may have been corrupted/write locked try rebooting and then deleting the image found in `%Homedrive%%Homepath%\Documents\Rainmeter\Skins\Monstercat-Visualizer\@Resources\images\coverGPMDP.png`

**Comment by tjhrulz** [comment] 2018-01-23 01:33
It seems it is an issue related to podcasts. I am investigating a fix for WebNowPlaying now and will likely submit a PR to the GPMDP Dev team as well if the issue is not isolated to just my plugin.

**Comment by tjhrulz** [comment] 2018-01-23 22:46
Found the source of the isse, for whatever reason Google appends -rwu-v1 to the end of podcast album art after size. If you try to load the max size image with that still appended it will fail. I have finished the patch for WebNowPlaying and am forking GPMDP so it may be fixed there.

I am going to leave this open and give status updates on the patches until they are all live.

**Comment by tjhrulz** [comment] 2018-01-24 18:14
Chrome update has been submitted and should be live in about an hour.
Doing some tweaks for the Firefox update now, should be submitted for verification here soon.
GPMDP devs have been notified of the issue and I am going to be resubmitting my patch shortly as my first build failed

**Comment by tjhrulz** [comment] 2018-01-26 12:14
Since the patch for Webnowplaying is live I'm going to go ahead and close this issue as the Google play music desktop player team typically takes a while before they push to live

**Closed** 2018-01-26 12:14 UTC
Labels: bug, external-issue, in review
