### ISSUE TITLE
The Title, Artist and Cover aren't working...

### ISSUE THREAD

**Issue by Dave12328** [MarcoPixel/Monstercat-Visualizer#195] opened 2018-07-22 21:24 UTC
### Description
Once I installed the visualizer, the Cover, Title, and Artist's name were not functioning with Spotify (Or any of the other media players I tried to use). I do not use an antivirus software, and I tried switching to Google DNS... I also Uninstalled and reinstalled Spotify in the Microsoft Store. None of these steps worked...

### Versions

I am currently using Visualizer version 2.0.2 
Rainmeter version 4.2.0
Spotify Plugin version is 2.1.5
My computer OS version is Windows 10 Pro 1803 64-bit (build 17134) - English (1033)

### Additional notes/images

![log](https://user-images.githubusercontent.com/26146545/43050270-43b0cb78-8dc3-11e8-9629-ae59d5f17c0d.PNG)

**Comment by BriancHawkins** [comment] 2018-07-23 00:39
I'm having the exact same problem. Been using this rainmeter program for about a year now, it just stopped showing the album cover and info about a week ago(?) or so? There was a spotify update around then, so I'm assuming that that's probably what threw a kink in the program and is causing it to fail at showing the info. Hopefully it's fixed soon, I absolutely love the program and there's not another one that will live up to it that I've found.

**Comment by MarcoPixel** [comment] 2018-07-23 00:39
Duplicate of #191

**Closed by MarcoPixel** 2018-07-23 00:39 UTC
