### ISSUE TITLE
after restart pc need to input the powershell script again

### ISSUE THREAD

**Issue by krazerian** [marcopixel/Monstercat-Visualizer#327] opened 2020-10-14 19:07 UTC
[IMPORTANT: Please remove or replace everything between two square brackets ( [ ] ) before posting your issue.]

### Description

[Please explain your problem here, tell all the step you've taken and how you found the issue.]

### Versions

[IMPORTANT: Please fill out the version numbers so we can properly look for your issue.]

[You can remove this section when posting an feature request]

* Rainmeter Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#VersionTab]
* OS Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#VersionTab]
* Skin Version: [You can check this here: Right-Click the Skin -> Open variables file. It should be at the top of the file]
* Spotify Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#PluginsTab]

### Additional notes/images

[If you have any additional infos you can give us, please write them down]

**Comment by marcopixel** [comment] 2020-10-23 08:23
Closing this issue, please either fill in more information to reopen this issue or if it's caused by [spicetify-cli](https://github.com/khanhas/spicetify-cli) please visit their repo for help.

**Closed by marcopixel** 2020-10-23 08:23 UTC
