### ISSUE TITLE
Cover Art, Artist and Song Name not showing up with Spotify

### ISSUE THREAD

**Issue by iltman** [MarcoPixel/Monstercat-Visualizer#216] opened 2018-08-27 03:56 UTC
I am having a problem getting the cover art and song title to show up using Spotify. The album art defaults to a white monster cat logo and the artist and song name both say N/A. I have tried updating to the latest version and reinstall the plugin and have also reinstalled Spotify. I've tried to switch to the google DNS and nothing seems to be blocking it in my hosts. The visualizer itself, however, is working fine and playing along to the music on Spotify. I don't know what else to do to fix this but I read the logs and there were a few errors. Maybe you can decipher them

Rainmeter Version: 4.2.0 r3111 64-bit (Jul 8 2018) -  English (1033)
OS Version: Windows 10 Home 1803 64-bit (build 17134) - English (1033)
Skin Version: 2.0.2
Spotify Version: 2.1.5

(Fetch error) The operation timed out  (ErrorCode=12002) (Monstercat-Visualizer\Song Information\Cover\Cover.ini - [MeasureWebParser])

(Fetch error) The operation timed out  (ErrorCode=12002) (Monstercat-Visualizer\visualizer.ini - [MeasureWebParser])

**Comment by MrGuffels** [comment] 2018-08-30 21:55
Same Issue

Rainmeter Version: 4.2.0 r3111 64-bit (Jul 8 2018) - English (1033)
OS Version: Microsoft Windows 10 Pro 10.0.17134 Build 17134
Skin Version: 2.0.2
Spotify Version: 1.0.88.353.g15c26ea1

(Fetch error) The operation timed out  (ErrorCode=12002) (Monstercat-Visualizer\visualizer.ini - [MeasureWebParser])

(Fetch error) The operation timed out  (ErrorCode=12002) (Monstercat-Visualizer\Song Information\Left.ini - [MeasureWebParser])

**Comment by ColonialDagger** [comment] 2018-09-03 15:16
Please see issue #191

**Comment by tjhrulz** [comment] 2018-09-11 00:18
Closing since duplicate of #191

**Closed by tjhrulz** 2018-09-11 00:18 UTC
