### ISSUE TITLE
How to get the media player to work (spotify)?

### ISSUE THREAD

**Issue by PizzaMaster007** [marcopixel/Monstercat-Visualizer#230] opened 2018-11-22 22:23 UTC
[IMPORTANT: Please remove or replace everything between two square brackets ( [ ] ) before posting your issue.]

### Description

[Please explain your problem here, tell all the step you've taken and how you found the issue.]

### Versions

[IMPORTANT: Please fill out the version numbers so we can properly look for your issue.]

[I understand that there are topics on this already but I am not still sure how to fix it so I am posting a new one (close mine and please refer me to the fix if there are new ones), I can't get the media player to show the album cover or the time but it does stop and play the song. Any fix?]

* Rainmeter Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#VersionTab]
* OS Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#VersionTab]
* Skin Version: [You can check this here: Right-Click the Skin -> Open variables file. It should be at the top of the file]
* Spotify Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#PluginsTab]

### Additional notes/images

[If you have any additional infos you can give us, please write them down]

**Comment by Linerly** [comment] 2019-02-22 15:29
### This is my way to make it work...
**Note: You can try this on Rainmeter 4.2 or Rainmeter 4.3 Beta...**

_Now this one is kinda weird but it'll work perfectly._

- First thing first download Spotify onto your computer. Then download this extension which is the WebNowPlaying Companion from Chrome by clicking [here.](https://chrome.google.com/webstore/detail/webnowplaying-companion/jfakgfcdgpghbbefmdfjkbdlibjgnbli)

- Once you are done downloading Spotify and the WebNowPlaying Companion extension, open Spotify in your browser by clicking [here.](https://open.spotify.com/) Now open Spotify on your computer makes sure that Spotify is closed to the tray bar.

- Use the web version of Spotify to play songs. Right-click the Monstercat Visualizer then click on "Open settings". Once you were done, go to "Media Player" in the Monstercat Visualizer settings. And click on "Web NowPlaying". Play any song in the web version of Spotify, and the visualizer should get the Spotify song information! I hope this is worked well... 😀

The result should be like this...
![screenshot_11](https://user-images.githubusercontent.com/47475676/53252330-383c3980-36f1-11e9-98df-bc777221af96.png)

**Comment by eerwwe** [comment] 2019-02-22 19:35
do i have to keep the web browser with spotify web player open and on to do this or can i close it after and use the desktop version?

**Comment by Linerly** [comment] 2019-02-24 03:33
> do i have to keep the web browser with spotify web player open and on to do this or can i close it after and use the desktop version?

@eerwwe, you need to keep the Web version of Spotify opened. To make it more convenient, you may want to open it after you open your web browser by going to:
Settings > On Startup > Choose "Open a specific page or set of pages" > Click "Add a new page" > Insert this link: https://open.spotify.com/collection/tracks

Like this:
![screenshot_12](https://user-images.githubusercontent.com/47475676/53294675-b564cd00-381d-11e9-9cdb-58b167ed0a47.png)

This is optional. If you want to use the web version of Spotify, In the desktop version of Spotify go to Menu > Settings > Advanced Settings > Startup and Window Behaviour > Select "Close button should minimize the Spotify window to the tray"

It should be like this:
![screenshot_13](https://user-images.githubusercontent.com/47475676/53294761-88191e80-381f-11e9-80b4-d3bd29893f79.png)

If you close Spotify in the desktop version, it should minimize the window to the tray.

**Comment by tjhrulz** [comment] 2019-05-04 06:03
Closing this due to it being a duplicate of issue #191 and for not following the guide for how to post an issue

**Closed by tjhrulz** 2019-05-04 06:03 UTC
