### ISSUE TITLE
Spotify Source not working and exhibiting strange behaviour.

### ISSUE THREAD

**Issue by Faunsce** [MarcoPixel/Monstercat-Visualizer#202] opened 2018-07-27 21:14 UTC
Description

Song info is always stuck on N/A, no audio, No album art will be displayed. This is when attempting to use the Spotify as source. When using WebNowPlaying, it works just fine as long as I use the Website version of spotify.

    Rainmeter Version: 4.2.0 Final Release - r3111 64-Bit - English (1033)

    OS Version: Windows 1803

    Skin Version: 2.02

    Spotify Version: 1.0.85.259.g4ab01679 (Windows Store version)

    Radian Linear Visualizer(Relevant Later, trust me): v1.9.3

          Additional Notes
Using the Beta 2! plugin by the guy who makes your plugin, made the audio visualization come back.

          More notes 
If I play from the spotify website while having audio running on the app itself, the visualiver will pull info from the site while the audio for the bars will come from the app, So i can have info like Ariana Grande and her album cover while a song like xxxTentacion - SAD! is having its audio visualized on the bars.

          Even more notes
After downloading Radian Linear, but not using their spotify plugin and sticking with the Beta 2 plugin, occasionally both visualizers will begin to receive the info and art for the song then both lose it after a few seconds. please note that both have continued to be able visualize the audio the whole time, just both have not been able to get info,

**Comment by Faunsce** [comment] 2018-07-27 22:19
[
![rainmeter_2018-07-27_17-52-17](https://user-images.githubusercontent.com/24751378/43347982-d27b681c-91c5-11e8-8ddc-6f6a937578e3.png)
](url)
![rainmeter_2018-07-27_18-04-18](https://user-images.githubusercontent.com/24751378/43348431-f89cafea-91c7-11e8-8730-1ed5ab89a8dc.png)
![rainmeter_2018-07-27_18-04-38](https://user-images.githubusercontent.com/24751378/43348432-f8a95a74-91c7-11e8-957f-c965c09a1108.png)
![rainmeter_2018-07-27_18-04-30](https://user-images.githubusercontent.com/24751378/43348433-f8b8fca4-91c7-11e8-94ff-620ab22c268c.png)

https://imgur.com/a/1Uac7EC <-- this gif if watched in whole, will show the player going from NotWork -> Work -> NotWork -> Work -> Not work.

**Comment by MarcoPixel** [comment] 2018-07-28 12:30
Duplicate of #191.

**Closed** 2018-07-28 12:30 UTC
