### ISSUE TITLE
Add support for Groove Music

### ISSUE THREAD

**Issue by jaybstorm** [MarcoPixel/Monstercat-Visualizer#155] opened 2018-03-24 13:26 UTC
Please add support for Groove Music in Windows 10.

**Comment by tjhrulz** [comment] 2018-03-24 17:01
Duplicate of #61 

1. Our stance is that we will not implement something into Monstercat Visualizer unless there is a plugin to support it.
2. It is not possible to do that with Groove Music, Microsoft is abandoning it and never finished the API for it enough that we would be able to control it anyway. The only other way possible would be using the volume on screen display but I have tried some windows hackery and there is no API (documented or not) that allows for reading another programs info it put in there.

**Closed by tjhrulz** 2018-03-24 17:01 UTC
Labels: duplicate, feature, wontfix
