### ISSUE TITLE
Visualizer bar gap not pixel perfect

### ISSUE THREAD

**Issue by Alipoodle** [MarcoPixel/Monstercat-Visualizer#49] opened 2017-05-14 12:16 UTC
With the settings I would normally use on Fountain of Rainbows seems to make, some but not all, of the Visualiser's bars overlap / have 0 spacing.
Settings:
![image](https://cloud.githubusercontent.com/assets/17199186/26033559/b920ed70-38a6-11e7-9f8a-719dc92b12ed.png)
Gif showing it off.
https://puu.sh/vPDRJ/9134780dea.gif
Image
![image](https://puu.sh/vPDT8/ffa3cceb51.png)

**Comment by tjhrulz** [comment] 2017-05-14 14:28
I think this is caused by the variable being set as a float instead of an int. What is the value of that setting in the variables.ini file? (Can be found under ~/Documents/Rainmeter/Skins/Monstercat-Visualizer/@resources/variables.ini)

**Comment by Alipoodle** [comment] 2017-05-14 14:54
My Variables.ini: https://pastebin.com/9a3XMwuC
``BarGap=1`` Which should work, if that helps?

**Comment by tjhrulz** [comment] 2017-05-14 15:09
Hmmm and bar width is also an int. Bar count is a float but I doubt that would cause it. I'll see if I can replicate the issue with a from scratch settings and see if I can find the exact cause.

After looking at the code I think it is something to do with the new rotate script as I see no references to the bar gap in it so I feel something may have been hard or miss coded or something.

**Comment by tjhrulz** [comment] 2017-05-14 16:01
Alright after looking into it it seems to be caused by pixel rounding of the rotation skin so they are not pixel perfect. This is more noticeable at smaller bar gaps but seems to occur at all gaps. @MarcoPixel any idea if alatsombath encountered issue like this that were resolved in future versions of fountain of colors?

**Comment by Alipoodle** [comment] 2017-05-14 16:20
![image](https://puu.sh/vPOLY/ac449767bc.png) Well towards the Rotate Script... would this help explain it....

**Comment by MarcoPixel** [comment] 2017-05-14 16:30
@tjhrulz This was because LUA rounded it wrong, should be fixed with the last commit.

**Comment by Alipoodle** [comment] 2017-05-14 16:38
I think this is due to the Math done for width
``W=(#CURRENTCONFIGWIDTH#-((#BarGap#*#ScaleVisualizer#)*2)+2)``
CurrentConfigWidth - (1*0.8)*2 + 2
CurrentConfigWidth - 3.6 
🤷‍♂️  Could this be the problem where it comes comes out wrong.

**Comment by tjhrulz** [comment] 2017-05-14 16:45
Better but now it is always one pixel larger than set and can not be a spacing of 0. Making line 13
local offset = math.ceil(barWidth) + math.ceil(barGap) -1
Seems to work tough in every edge case and is still pixel perfect.

**Comment by MarcoPixel** [comment] 2017-05-14 17:04
Hmm, @tjhrulz i've tried it and it worked flawlessly on lower numbers but when you do higher ones it will break again. Maybe it has to do something with the width like @Alipoodle said.

**Comment by tjhrulz** [comment] 2017-05-15 00:00
How is it breaking? Seems to work fine on my end even at large numbers. Is it just not pixel perfect? It is hard to tell if it is but I can get out photoshop just to double check

**Comment by tjhrulz** [comment] 2017-05-15 00:02
I think I just found the real issue to this, the bar width is actually 1 pixel less than it is supposed to be.

**Comment by tjhrulz** [comment] 2017-05-15 05:08
Also @Alipoodle that weird string is due to an encoding issue that is actually the degrees symbol being misencoded in github, we should probably fix that @MarcoPixel.

**Comment by MarcoPixel** [comment] 2017-06-04 17:48
Fixed with 1.7.1 release, please download the update and report back if it is fixed for you.

**Closed by MarcoPixel** 2017-06-04 17:48 UTC
Labels: bug, in review
