### ISSUE TITLE
Spotify not working at all

### ISSUE THREAD

**Issue by ASAPKush** [MarcoPixel/Monstercat-Visualizer#29] opened 2017-03-11 10:09 UTC
My album cover shows AWD Winterride enhanced cover and I've never heard of it and when I click windows audio player it changes to the normal monstercat grey thing.. I reinstalled ran as admin reinstalled rainmeter and monstercat visualizer including all the dlls and refreshed everything nothings worked.

**Comment by MarcoPixel** [comment] 2017-03-11 10:28
Duplicate of #27, closed.

**Closed by MarcoPixel** 2017-03-11 10:28 UTC
