### ISSUE TITLE
iTunes having issues getting song data, getting stuck after song change

### ISSUE THREAD

**Issue by Paulchen1409** [MarcoPixel/Monstercat-Visualizer#115] opened 2017-11-17 23:40 UTC
Hello,
the visualizer does not hide even if I close itunes. I have the auto hide option enabled.
Is this my fault?

**Comment by MarcoPixel** [comment] 2017-11-18 17:36
Hello!

It's probably not your fault ;)

I would assume that **iTunes is somehow reporting the player state wrong** and this will break the Auto-Hide option. As we currently have a lot of issues regarding iTunes as some recent changes broke something, **we don't have a fix for now**. 

As soon as we found the cause of the issues, we will keep everyone up-to-date who is **subscribed** to this issue (You can subscribe by clicking on the button on the right)

**Comment by tjhrulz** [comment] 2017-11-20 02:27
The 4.2 beta fixes a lot of the remaining stale data issues. Let me know if you still have any issues after updating.

**Comment by Paulchen1409** [comment] 2017-11-21 15:33
Now the autohide feature works. But sometimes the visualizer won't reappear

**Comment by Paulchen1409** [comment] 2017-11-22 14:35
And with the Beta, the Visualizer starts to lag.

**Comment by tjhrulz** [comment] 2017-11-22 17:00
Visualizer lag is likely unrelated given the changes we made. I will look into the itunes open issue though, probably will get a chance tomorrow.

**Comment by tjhrulz** [comment] 2017-12-12 01:20
All these issues should be resolved in Rainmeter 4.2 Beta Release - r3004. The only minor issue is that Rainmeter can lockup for a second or so when you close iTunes but that is Apple's fault.

**Closed by tjhrulz** 2017-12-12 01:20 UTC
Labels: bug, external-issue, in review
