### ISSUE TITLE
Memory Leak with GP desktop

### ISSUE THREAD

**Issue by OttoDeFe** [MarcoPixel/Monstercat-Visualizer#17] opened 2017-02-10 03:10 UTC
The memory leak is better with the new build, but still ate 7 gigs of RAM during a 10 hour day.

**Comment by tjhrulz** [comment] 2017-02-10 03:45
Odd I don't think it should be from the same cause as before, under what circumstances is it leaking?

**Comment by tjhrulz** [comment] 2017-02-10 03:49
Also can you pull up the about window for rainmeter go to the plugin tab and tell me what version of my plugin you are running?

**Comment by OttoDeFe** [comment] 2017-02-10 03:52
I opened the player, loaded the skin and then closed the player and went to
work. I had installed the new build and restarted Rainmeter before I
started. The rate of increase when I left for work was about 100 KB a tick
according to the task manager.

**Comment by tjhrulz** [comment] 2017-02-10 04:10
Alright I am trying to replicate it now and not getting anything but maybe it has something to do with opening and then closing it the causes the issue. Also my skin I use personally the memory leak was less obvious before so I am going to load up the Monstercat Visualizer as well and hopefully that should help me find this bug.

Just checking when you say closed do you mean fully closed (Like it was not running in your taskbar and there were no executables for GPMDP listed in the task manager) or just the window was closed.
Also as I said above if you could double check with me that version that way I can make sure any changes I made since then did not accidently fix it as I have not updated Monstercat Visualizer to the current version as it is still for testing.

**Comment by OttoDeFe** [comment] 2017-02-10 04:40
The version I downloaded from GitHub is 1.5.3 - I extracted the zip and
overwrote all the files for the skin. I shutdown Rainmeter, and restarted
it, opened the GPMDP, loaded the skin, and made sure all was working. I
then shutdown the player completely. I opened the taskmanager and saw the
slow climb in memory usage. I went to work and when I got home it had
consumed the RAM, but not nearly like it had at first (it had consumed my
RAM to 99% in less than 8 hours).

**Comment by tjhrulz** [comment] 2017-02-10 04:47
Oh I meant the version of my plugin. 

However it sounds like what you did would not have fixed the issue as my plugin was not updated so that is why you are still having the problem and I can not reproduce it. To do that you have to go through the rmskin installer and updating my plugin. Or if you do a manual install do it by moving the GPMDPPlugin.dll from the correct .installer/plugins folder (x86 if 32bit x64 if 64bit) to ~/appdata/roaming/rainmeter/plugins/

**Closed by tjhrulz** 2017-02-10 04:47 UTC
Labels: bug, in review

**Comment by OttoDeFe** [comment] 2017-02-10 04:57
That did it... completely spaced on the installer. still pretty inexperienced with Rainmeter.  Thanks for all the help and sorry to have troubled you.

**Comment by tjhrulz** [comment] 2017-02-10 05:00
Its all good man we all have those days. Besides you got me to make a cup of coffee and now I am getting some stuff I needed to get done anyways. Glad I was able to resolve your issue though and hopefully someone in the future will have the same issue and find this thread.
