### ISSUE TITLE
Visualizer still not working after following troubleshooting

### ISSUE THREAD

**Issue by Gabrion** [MarcoPixel/Monstercat-Visualizer#64] opened 2017-06-16 18:49 UTC
Hello, I have been having some problems with the Visualizer not working at all. I have went through the troubleshooting guide (https://forum.rainmeter.net/viewtopic.php?p=123883#p123883) I have tried every thing but trying to run in stereo 48khz and manually putting the id of my device into the visualizer skin, both of which i do not know how to do. also reguarding step 2 where it provides a skin to check if the problem is not apart of the visualizer itself does nothing but my other visualizer does pick up sounds, being it from Spotify or from iTunes

Help would be very much appreciated!

**Comment by MarcoPixel** [comment] 2017-06-16 19:09
Hello!

Did you already try increasing the Sensitivity in the settings skin and then refreshing the skin?

If that didn't work, please send a screenshot from the debug log of Rainmeter (https://docs.rainmeter.net/manual/user-interface/about/) and post it in here.

Also please write down your OS version, Rainmeter version and skin version.

**Comment by Gabrion** [comment] 2017-06-16 19:19
Yes i have tried that and it made no difference. http://imgur.com/a/Pp3ko (here is the log)

I am using Windows 10, Rainmeter version 4.1.0 beta r2807 64-bit. the skin version is 1.7.0

**Comment by MarcoPixel** [comment] 2017-06-19 17:41
Hmm, that really sounds kinda weird. If other skins are getting audio data it should show on mine too, the only difference can be the sensitivity and device ID. Did you also try reinstalling Rainmeter and check if that fixed it?

**Comment by Gabrion** [comment] 2017-06-19 19:41
I have just tried another clean install of Rainmeter and there is still no difference except now when i tried to install another Visualizer skin as a test it wouldn't react either :/

**Comment by tjhrulz** [comment] 2017-06-26 18:00
Then that sounds like an issue with the AudioLevel plugin itself and the Monstercat Visualizer's implementation of it. Try going through the troubleshooting guide again and maybe getting in touch with Active Color.

**Comment by MarcoPixel** [comment] 2017-07-24 19:32
It seems that the issue is solved now as there wasn't any response since 19th of June so i'm gonna close it for now.

**Closed by MarcoPixel** 2017-07-24 19:32 UTC
Labels: bug
