### ISSUE TITLE
Smart player switch?

### ISSUE THREAD

**Issue by SetyGames** [MarcoPixel/Monstercat-Visualizer#21] opened 2017-02-22 01:05 UTC
I would like a feature where if you have Spotify open but you have your player set as foobar2000 it will display the song name from Spotify instead of foobar2000 and vice versa. Almost like the smart player switch in [Cleartext](http://redsaph.deviantart.com/art/Cleartext-for-Rainmeter-v3-3-0-21-Dec-2016-519796161) where you can choose a secondary player.

This would be great for people who use both Spotify and another player at the same time, like me.

**Comment by tjhrulz** [comment] 2017-02-22 02:11
The way the code base currently is this would be doable however the check to see if the player is running can be computationally expensive especially if doing it for every supported player, we could make it dynamically switch between plugins using the player state but then it would not switch between the normal rainmeter players. 

The idea though of having a secondary player does sound more efficient. I'll make a fork and look into the performance of the two different ways to implement it and report the performance back here and see if Marco wants to merge it.

**Comment by tjhrulz** [comment] 2017-02-24 18:30
Alright so after some testing the CPU usage is not as bad as I expected it to be and it basically has no impact on CPU performance. However I did not think about the fact that we dynamically include the measures for the music info does mean that this is going to require including ever player measure on load of the skin. However I think I can manipulate them in a way that won't major extra CPU but it is going to take rewriting a decent amount of code and changing the way the code works.

After talking to marco I think once I get it up and running in a day or two we will make an experimental branch for it and you will be able to download it there.

**Comment by SetyGames** [comment] 2017-02-25 06:20
Alright, great! Lets hope it works out :smile:

**Comment by tjhrulz** [comment] 2017-03-07 20:16
Hey sorry for not getting back sooner but I kinda ran into a bug that I could never fix with the version and moved on to another project I was wanting to work on. The bug basically is when going from GPMDP to iTunes the plugin to use does not want to update but going from spotify to iTunes works fine. I think it has something to do with my regular expressions. Ill try to see if I can fix that sometime this week. Once that bug is fixed it is pretty much done.

**Comment by SetyGames** [comment] 2017-03-10 15:06
Ah ok.

**Comment by SetyGames** [comment] 2017-04-02 14:43
Any updates?

**Comment by GMR516** [comment] 2017-04-04 15:23
I would like to know any updates on this as well. What's up?

**Comment by MarcoPixel** [comment] 2017-04-04 15:53
As @tjhrulz was working on this issue, i can not tell you if he's still working on this or if he abandoned it. If he doesnt want to continue, i will close this issue as this feature is quite expensive to create and also maintain in the future.

If he is not responding to this in the next few days, i'm gonna close it and keep a link to his repo where you can try to develop on this feature yourself and if you get it to work propertly you can try and send an pull request to get it merged to the main repo.

His repo: https://github.com/tjhrulz/Monstercat-Visualizer

**Comment by tjhrulz** [comment] 2017-04-04 16:08
Yeah sorry my GitHub app had signed me out so I was not getting notifications the last few days. 

The issue is I could never figure out what was causing the bad switching bug and I assume the same thing would happen with other sources. If you want to look at it and see if you can figure it out be my guest but I have been busy working on other projects recently.

**Comment by MarcoPixel** [comment] 2017-04-07 22:26
I will close this issue for now as @tjhrulz is busy with other projects and can not continue with the skin right now.

If there is a better and easier way to implement this feature, please reopen this issue or send an pull request with your changes.

**Closed by MarcoPixel** 2017-04-07 22:26 UTC
Labels: feature, in review, request
