### ISSUE TITLE
Song Information & Albumart missing 

### ISSUE THREAD

**Issue by derAndere87** [MarcoPixel/Monstercat-Visualizer#209] opened 2018-08-12 09:45 UTC
### Description

I don't when it happened but I just noticed it. I no longer have the Albumart showing nor the Songinfo just N/A. Controls and Visualization are still working fine. I'm kind of clueless here.

### Versions

* Rainmeter Version: 4.2.0 r3111 64bit
* OS Version: Windows 10 64bit 1803
* Skin Version: 2.0.2
* Spotify Version: 1.0.87.491.ge2a121fc

**Comment by YoussefZayed** [comment] 2018-08-16 01:40
I also have the same problem, clean install as well.

**Comment by MarcoPixel** [comment] 2018-08-17 16:35
Duplicate of #191.

**Closed by MarcoPixel** 2018-08-17 16:35 UTC
