### ISSUE TITLE
Spotify Song Info Not Working

### ISSUE THREAD

**Issue by SociallyIneptLoser** [MarcoPixel/Monstercat-Visualizer#217] opened 2018-09-01 20:34 UTC
### Description

The visualizer itself works fine but the song info (album cover, song title, and artist) isn't working. And simply displaying N/A and the monstercat logo.

### Versions

* Rainmeter Version: 4.2.0 beta r3088 64-bit (Jun 15 2018) - English (1033)

* OS Version: Windows 10 Home 1803 64-bit (build 17134) - English (4105)

* Skin Version: 2.0.2

* Spotify Version: 2.1.5

### Additional notes/images

I've tried reinstalling Spotify, restarting my computer, and restarting rainmeter.

**Comment by ColonialDagger** [comment] 2018-09-03 15:16
Please see issue #191

**Comment by tjhrulz** [comment] 2018-09-11 00:17
Closing since duplicate of #191

**Closed by tjhrulz** 2018-09-11 00:17 UTC
