### ISSUE TITLE
Youtube 

### ISSUE THREAD

**Issue by Batgoonz** [MarcoPixel/Monstercat-Visualizer#332] opened 2020-11-29 06:04 UTC
[ **IMPORTANT: Please remove or replace everything between two square brackets ( [ ] ) before posting your issue.** ]

### Describe the bug
[ Whenever I exit a video in youtube or go back to youtube home, the channel name duplicates and shows another copy at the bottom. When I play another video, it goes back to normal. ]

### Screenshots
When exiting a video or going to youtube home
![Capture](https://user-images.githubusercontent.com/75195555/100534558-33ec6b00-324b-11eb-9019-2180fcc61b24.PNG) ]

When Playing a youtube video
![Capture](https://user-images.githubusercontent.com/75195555/100534668-634fa780-324c-11eb-8d9b-8d95d128b597.PNG)

### System information
* **Rainmeter Version:** [Latest Final Version]

**Comment by marcopixel** [comment] 2020-11-29 08:47
Duplicate of #330, please follow the steps there for further help.

**Closed as completed by marcopixel** 2020-11-29 08:47 UTC
Labels: bug
