### ISSUE TITLE
Spotify Plugin Not Working

### ISSUE THREAD

**Issue by RageYT** [MarcoPixel/Monstercat-Visualizer#207] opened 2018-08-05 23:29 UTC
### Description

Following the instructions given, I've installed the SpotifyPlugin and tried using the Spotify option given in the media player selection. Even though I've selected it, nothing happens and the visualizer still picks up all my audio as it would on first install.

### Versions

* Rainmeter Version: 4.2.0 r3111
* OS Version: Windows 10 home (build 17134)
* Skin Version: 2.0.2
* Spotify Version: 2.1.5

**Comment by MarcoPixel** [comment] 2018-08-17 16:35
Duplicate of #191.

**Closed by MarcoPixel** 2018-08-17 16:35 UTC
