### ISSUE TITLE
2.0.1 bugs that I've found when I updated from 1.8.1

### ISSUE THREAD

**Issue by ScratchHacker1** [MarcoPixel/Monstercat-Visualizer#176] opened 2018-06-10 14:36 UTC
### Description
So I've recently updated to the newest version of the visualizer (2.0.1) and I've found some bugs...

1. End of the visualizer buggs out when using 98 bars but is fine when using 97
2. Artist name/Song name cant be dragged horizontaly (Maybe I'm dumb and you can. If so please let me know)
3. The pause/play button doesn't always work (So the animation doesn't always work and the function doesn't always work)
### Versions

* Rainmeter Version: 4.2.0 beta r3074 64-bit
* OS Version: Windows 10 Pro 1803 64-bit (Build 17134)
* Skin Version: 2.0.1
* iTunes version: 12.7.5.9

### Additional notes/images
![image](https://user-images.githubusercontent.com/33940501/41202628-b0712c86-6cd4-11e8-915e-d77b7413ca82.png)

**Comment by MarcoPixel** [comment] 2018-06-13 09:58
1. Duplicate of #126, try the steps there and see if they work. Couldn't reproduce it on my system, so it might be an issue with your system/audio driver.

2. You can't drag them because you have "Clip Song Information" enabled and since your bars span the whole desktop, they cannot be moved as the skin is the same size as the visualizer now. DIsable this in the settings and you should be able to move them around again.

3. Should be fixed with https://github.com/MarcoPixel/Monstercat-Visualizer/commit/19967bf01cf522ea303e399d604199e95ff013ba in the next update, stay tuned!

**Closed by MarcoPixel** 2018-06-13 09:58 UTC

**Comment by MarcoPixel** [comment] 2018-06-23 12:09
**Quick update on Issue 2:** I've identified another issue causing your problem and it should be fixed with 2.0.3 which should come soon :)

Bugfix commit: https://github.com/MarcoPixel/Monstercat-Visualizer/commit/5a876cfb568f2ddfcbe31a49513b4a7d456fa13c
