### ISSUE TITLE
Issue with Cover not working properly

### ISSUE THREAD

**Issue by CodexWarz** [MarcoPixel/Monstercat-Visualizer#147] opened 2018-03-15 01:36 UTC
### Description

The cover buttons don't actually work with spotify. For example if i click pause or back skip or forward skip, nothing happens.

### Versions

1.8.1

* Rainmeter Version: 4.1 r2989
* OS Version: Windows 10 64 bit
* Skin Version: 1.8.1
* Spotify Version: 1.0.75.483.g7ff4a0dc

### Additional notes/images

The album cover is working just fine and you can see the buttons when you scroll over them and your mouse makes it look like it's clickable.

![capture](https://user-images.githubusercontent.com/19767601/37439695-3cca7b40-27c7-11e8-86cb-375def6c13e1.JPG)

**Comment by MarcoPixel** [comment] 2018-03-15 13:45
Duplicate of #144.

**Closed by MarcoPixel** 2018-03-15 13:45 UTC
